language: perl
perl:
  - '5.19'
  - '5.18'
  - '5.16'
  - '5.14'
  - '5.12'
  - '5.10'
  - '5.8.9'
  - '5.8.4'
  - '5.8.1'
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=0
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
script:
  - perl Makefile.PL
  - make
  - prove -l $(test-dirs)

